[Feature] Extract iteration result based on the payload found in output instead of requester
Zigrin-Security/CakeFuzzer pull request #9
Opened 2023-06-01 07:12 UTC by Bobowski

# Description

In order to find vulnerabilities that were triggered by one scenario but found in other requests' response we need to change the way we extract iteration results while building vulnerabilities list. The change is just to check if the payload_guild found in vulnerability is actually coming from the execution that it's linked to, it they are then it's just a standard case for "this request caused this vulnerability" in other case we need to extract different iteration_result (based on the payload_guid because altho we found the vulnerability in this output it was not caused by this request.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Yes, it's simple logical change. 

# Checklist:

- [ ] PR title contains the nature of changes (Docs, Feature, Fix, CI, etc.)
- [ ] I've set corresponding reviewers, set assignees, and labels.
- [ ] My code follows the style guidelines of this project (running `pre-commit`)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-01 10:17 UTC, jjakiteli approved these changes

2023-06-02 13:56 UTC, dawid-czarnecki requested changes
This has to be tested once annotations are properly removed. Here is a quick patch on cerebrate that introduce stored XSS. Injection in `/AuthKeys/add`, exploitation in `/AuditLogs/index`:
```
diff --git a/src/Controller/AuditLogsController.php b/src/Controller/AuditLogsController.php
index e3e4e0ce..85709159 100644
--- a/src/Controller/AuditLogsController.php
+++ b/src/Controller/AuditLogsController.php
@@ -17,6 +17,17 @@ class AuditLogsController extends AppController
 
     public function index()
     {
+        $keys = $this->getTableLocator()->get('AuthKeys');
+        $all = $keys->find()->all();
+        if($all->count()>0) {
+            $all = $all->toArray();
+            foreach($all as $key) {
+                $id = $key->get('id');
+                $comment = $key->get('comment');
+                print("Key: $id. Comment: $comment<br>\n");
+            }
+            die;
+        }
         $this->CRUD->index([
             'contain' => $this->containFields,
             'order' => ['AuditLogs.id' => 'DESC'],
```

2023-07-19 10:14 UTC, Bobowski commented on cakefuzzer/domain/components.py
> +                        "strategy_name": vuln.iteration_result.scenario.strategy_name,
add "found_in" as to have a common dict structure

2023-07-19 13:52 UTC, dawid-czarnecki requested changes
Other than that the PR is ready to merge. No need to change `results.json` more at this point.

2023-07-19 13:52 UTC, dawid-czarnecki commented on cakefuzzer/domain/components.py
> +                            "context_location": vuln.vulnerability.context_location,
These can be removed

2023-07-19 13:52 UTC, dawid-czarnecki commented on cakefuzzer/domain/components.py
> +                            "payload": vuln.found_in_iteration_result.scenario.payload,
This can be removed.

2023-07-19 13:52 UTC, dawid-czarnecki commented on cakefuzzer/domain/components.py
> +                            "vulnerability_id": i,
This can be removed.

2023-07-29 11:56 UTC, dawid-czarnecki approved these changes
LGTM

2023-07-31 10:26 UTC, merged